// <auto-generated />
using Ecom.Services.ProductApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecom.Services.ProductApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240516173210_AddsProductTable")]
    partial class AddsProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecom.Services.ProductApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Smart Phone",
                            Description = "This is the description of iPhone 12",
                            ImageUrl = "product-1.png",
                            Name = "IPhone 12",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Smart Phone",
                            Description = "This is the description of Samsung Galaxy S20",
                            ImageUrl = "product-2.png",
                            Name = "Samsung Galaxy S20",
                            Price = 900.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Smart Phone",
                            Description = "This is the description of Huawei P30",
                            ImageUrl = "product-3.png",
                            Name = "Huawei P30",
                            Price = 800.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Smart Phone",
                            Description = "This is the description of Xiaomi Mi 10",
                            ImageUrl = "product-4.png",
                            Name = "Xiaomi Mi 10",
                            Price = 700.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Smart Phone",
                            Description = "This is the description of OnePlus 8",
                            ImageUrl = "product-5.png",
                            Name = "OnePlus 8",
                            Price = 600.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
